### ISSUE TITLE
Installation from pip is ambiguous

### ISSUE THREAD

**Issue by botherder** [blockadeio/analyst_toolbench#1]
The instructions provided on how to install from pip seem ambiguous. The script blockade-cfg doesn't seem to be provided uniquely by installing `pip install blockade` but seems to require `pip install blockade-toolkit` as well. If correct, this should probably reflect in the README, or otherwise be clarified.

**Comment by 9b** [comment]
Just fixed in c2f3861. Had a typo on the package installation. Installing the toolkit will get you everything you need.
