### ISSUE TITLE
Add ability to specify the cloud node through blockade-cfg

### ISSUE THREAD

**Issue by botherder** [blockadeio/analyst_toolbench#2]
The blockade-cfg doesn't seem to be able to provide a way to specify which cloud node the account is for. In that regard, should probably consider an appropriate way to support multiple accounts on multiple cloud nodes.

**Comment by 9b** [comment]
Good catch. I had initially planned to only have one server in place. I'll update so the setup allows you to change out the cloud URL. Need a better way to manage multiple connections though.
